# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Federico Niccoló Daverio
title: Economist and Data Analyst
email: daveriofederico@gmail.com
website: www.federicodaverio.github.io
# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: FedeDave1
github_username:  FedericoDaverio
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: federicodaverio
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Spanish
  icon: fas fa-language
  url: https://www.federicodaverio.github.io/spanish
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/prueba1.PNG
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Federico and I'm an Economist and Data Analyst. I graduated in 2021 from the Development Economic Masters Program at [CIDE](https://www.cide.edu/).
  
  Formerly I studied engineering (BSc) and Supply Chain Management (Msc) at [Politecnico di Milano](https://www.polimi.it/) in Milan and Seville. 
  
  I'm comitted to social causes and I love challenges as long learn day by day. I am interested in Public Policies, Development, Inequality, Social Program evaluation, Income distribution and Poverty and Urban Economics. I have worked on the effect of urban marginality on individual's employment results and the role of leaders during the Covid-19 pandemic. Here you can     
  
  Here you can find my ["Accademic CV"](https://github.com/FedericoDaverio/federicodaverio.github.io/blob/main/CV_Accademic_FD.pdf) or a ["More colorful" one](https://github.com/FedericoDaverio/federicodaverio.github.io/blob/main/Federico_Daverio_CV_c.pdf)

  I am most skilled in: <mark>Problem Solving</mark> and <mark>Eating Pizza</mark>

content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: CIDE
        link: cide.edu
        #link_text: cide
        sub_title: Research and Teaching Assistant
        caption: July 2020 - Present
        quote: >
          Public center of teaching and investgation in economics
        description: | # this will include new lines to allow paragraphs
            During the master I start to work with a SNI researcher in his investigation, helping with data analysis and developing algorithms for social programs evaluation. Meanwhile I’m teaching the “Introduction to Data Science” laboratory.
      - layout: left
        title: Studio Ceri
        link: studioceri.it
        #link_text: cide
        sub_title: Supply Chain Coordinator Mexico
        caption: August 2013 - September 2019
        quote: >
          Studio Ceri is an Italian leader in interior design focused on export the italian excelence to the world.
        description: | # this will include new lines to allow paragraphs
             When Studio Ceri decided to expand its business in México by buying an 28000 m2 warehouse, I was in charge of coordinating the whole supply chain and developing the necessary IT infrastructure. My current was Mexico Supply Chain Director, supervising purchasing, national logistic and warehouse division.
      - layout: left
        title: Accenture
        link: accenture.com
        #link_text: cide
        sub_title: Research and Teaching Assistant
        caption: November 2012 - August 2013
        quote: >
          To deliver on the promise of technology. Consulting and professional services. 
        description: | # this will include new lines to allow paragraphs
              I joined a team working on a Fincantieri’s project. My main task was to develop a forecasting tool to make more accurate calculation of the costs and of material consumption in the making of a new cruise. I found this experience extremely stimulating, especially because of the very challenging and competitive environment.        
       
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: CIDE
        caption: 2019 - 2021
        sub_title: MSc Development Economics
        quote: >
          The Centre for Investigation and Education of Economics is one of the best mexican economic university.
        description: | # this will include new lines to allow paragraphs
          Final Grade: 9.6/10
          
      - layout: left
        title: POLIMI
        caption: 2010 - 2013
        sub_title: MSc Supply Chain Management
        quote: >
          Established in 1863, Politecnico di Milano is the 20th university in the world in engineering and technology field. 
        description: | # this will include new lines to allow paragraphs
           Final Grade: 109/110
      - layout: left
        title: POLIMI
        caption: 2007 - 2010
        sub_title: BSc Management and Production Engineering
        quote: >
          Established in 1863, Politecnico di Milano is the 20th university in the world in engineering and technology field. 
        description: | # this will include new lines to allow paragraphs
           Final Grade: 104/110
          
  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Languages
        description: | # this will include new lines to allow paragraphs
          Italian (Mother tongue), Spanish (Expert), English (Advanced), Portuguese (Beginner)
      - layout: left
        title: Programming
        description: | # this will include new lines to allow paragraphs
          R (Advanced), Python (Advanced), SQL (Intermediate), Stata (Intermediate), Html/Css (Basic), Excel/VBA (Advanced)
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: NuestrasVoces
        link: nuestrasvoces.mx
        # link_text: Project Website
        additional_links:
          - title:  nuestrasvoces.mx
            icon: fab fa-globe
            url: nuestrasvoces.mx
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          We try to rescue the voices of Mexican women from the present and the past 
        description: | # this will include new lines to allow paragraphs
          I collaborate in this project aimed to discover and share Mexican women story so to be an example and inspiration for nowdays generations. I partecipate devoleping the site and the CEO startegy. 

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in economics and data analysis some of my other interests and hobbies are:
      - Running
      - Reading
      - Traveling
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

     
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
